fix: rename `aarch64` to `arm64` on Linux.
chessmango/asdf-flyctl pull request #2
Opened 2023-02-22 21:14 UTC by jimsynz

Closes #1.

2023-02-23 12:05 UTC, chessmango requested changes
Thanks for the PR! Glad to see this is in use somewhere as well :)
Just suggesting being less specific for ease, and then in case something other than Linux reports `aarch64` for whatever reason.

2023-02-23 12:05 UTC, chessmango commented on lib/utils.bash
> +  fi
Given this applies to Mac too (though [Wikipedia's uname examples](https://en.wikipedia.org/wiki/Uname) suggest `arm64`) we can probably afford to be broad here and avoid an extra platform check:

```suggestion
  local arch
  arch=$(uname -m)

  if [[ "$arch" == "aarch64" ]]; then
    echo "arm64"
  else
    echo "$arch"
  fi
```

2023-02-23 20:34 UTC, jimsynz commented
Thanks man. Yeah, I use ASDF in all my devcontainers because we can manage the environment from a single tool versions file. Had a client that deploys via fly - easy enough to add to the container this way.

2023-02-24 19:49 UTC, merged

2023-02-24 19:57 UTC, chessmango commented
> Thanks man. Yeah, I use ASDF in all my devcontainers because we can manage the environment from a single tool versions file. Had a client that deploys via fly - easy enough to add to the container this way.

Very cool. I'm trying to find ways to have my org do the same, but plugin quality varies pretty wildly. Mine probably aren't the greatest either ;) though I try to keep things consistent at least

Thanks again for the PR!